### ISSUE TITLE
斐讯 N1 Armbian 一键脚本安装Lucky服务无法启动！

### ISSUE THREAD

**Issue by KoWming** [gdy666/lucky-files#1]
![微信截图_20220801112640](https://user-images.githubusercontent.com/96684377/182066840-5a6753a7-328f-4078-9e5f-51fa57bfc12e.png)
![微信图片_20220801112347](https://user-images.githubusercontent.com/96684377/182066857-de7ab84e-71d0-4a02-b478-7943b2deb8de.png)

“设为systemd方式启动
sysdir:/usr/lib/systemd/system
检测超时，请自行检查lucky运行情况”

查看进程和端口占用情况没发现Lucky运行起来，不知道是不是我的armbian 缺少Lucky所需依赖！

**Comment by gdy666** [comment]
安装完后你试试用命令
/etc/lucky.daji/lucky -c /etc/lucky.daji/lucky.conf &
看看能不能运行起来?
不同环境有点折腾人...还是得去搞搞docker...

**Comment by KoWming** [comment]
> 安装完后你试试用命令 /etc/lucky.daji/lucky -c /etc/lucky.daji/lucky.conf & 看看能不能运行起来? 不同环境有点折腾人...还是得去搞搞docker...

我晕，之前安装了几次都没启动成功，现在安装有运行成功了！！！应该是之前网络原因下载文件不完整！

不过大佬如果能做成docker，各平台兼容应该会更好，部署、管理起来也会更方便些吧！期待大佬的docker版本，有时间在做。

请输入相应数字 > 1
目标目录/etc空间剩余：3.5G
确认安装？(1/0) > 1
luckdir:/etc/lucky.daji
--2022-08-01 14:33:02--  https://fastly.jsdelivr.net/gh/gdy666/lucky-files@main/1.1.6/lucky_1.1.6_Linux_arm64.tar.gz
Resolving fastly.jsdelivr.net (fastly.jsdelivr.net)... 2a04:4e42::485, 2a04, ...
Connecting to fastly.jsdelivr.net (fastly.jsdelivr.net)|2a04:4e42::485|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2476909 (2.4M) [application/gzip]
Saving to: ‘/tmp/lucky.tar.gz’

/tmp/lucky.tar.gz             100%[==============================================>]   2.36M  1.81MB/s    in 1.3s    

2022-08-01 14:33:05 (1.81 MB/s) - ‘/tmp/lucky.tar.gz’ saved [2476909/2476909]

-----------------------------------------------
开始解压文件！
LICENSE
scripts/lucky.service
scripts/luckyservice
scripts/misnap_init.sh
lucky
已解压到 /etc/lucky.daji
Profile:/etc/profile
设为systemd方式启动
sysdir:/usr/lib/systemd/system
Created symlink /etc/systemd/system/multi-user.target.wants/lucky.daji.service → /lib/systemd/system/lucky.daji.service.
lucky已成功运行
