### ISSUE TITLE
能用在华硕路由器上吗？

### ISSUE THREAD

**Issue by maxage** [gdy666/lucky-files#2]
大佬~能用在华硕ax86u的软件商店里面吗？

**Comment by gdy666** [comment]
软件商店里面没有,得打开SSH,执行一次安装指令,我在刷了梅林的r7000测试安装没问题.

**Comment by yanquan2020** [comment]
这软件一定是得路由器拨号吗?路由器桥接下的局域网内的n1装docker版本是不是用不了的,穿透不了？
这边只有安装说明，使用说明太少太简单了。。。
