### ISSUE TITLE
这软件一定是得路由器拨号吗?

### ISSUE THREAD

**Issue by yanquan2020** [gdy666/lucky-files#4]
这软件一定是得路由器拨号吗?光猫拨号，路由器连接下的局域网内的n1装docker版本是不是用不了的,穿透不了？
这边只有安装说明，使用说明太少太简单了。。。

**Comment by gdy666** [comment]
运行网络环境可以参考下面这个软件的readme.
https://github.com/MikeWang000000/Natter
光猫拨号可以尝试在光猫设置DMZ指向路由,路由再设置DMZ指向n1.
如果还不行的话就当我没说....毕竟每个人的网络都不一样,我没法详细一一解决.
